#' @include utilities.R
NULL
#'Normalize Counts Data Using DESeq2
#'@description Normalize Counts Data Using DESeq2.
#'@param data a list containing the following component: raw.count, count.norm
#'  and count.rlog. Genrally an object of class normalize_counts as generated by
#'  the function normalize_counts().
#'@return Return an object of class SummarizedExperiment.
#'@param result.dir a directory to save the output.
#'@return Create a pdf file "quality.control.pdf" containing the results of the
#'  quality assessment.
#'@export
check_count_data <- function(data, result.dir = "COUNT"){

  if(!inherits(data, c("normalize_counts", "list")))
    stop("data should be an object of class normalize_counts as generated by the function normalize_counts().")

  dir.create(result.dir, showWarnings = FALSE, recursive = TRUE)
  raw.count <- data$raw.count
  count.norm <- data$count.norm
  rld.data <- data$count.rlog

  # Quality Control
  # ++++++++++++++++++++++++++++
  message("- Generating Quality Control File...\n")
  nsamples <- ncol(count.norm)

  if(nsamples >= 2){
    expressed.genes <- rowSums(raw.count) > 0
    raw.count <- raw.count[expressed.genes, , drop = FALSE]
    count.norm <- count.norm[expressed.genes, , drop = FALSE]
    rld.data <- rld.data[expressed.genes, , drop = FALSE]

    # Number of mapped read counts per sample
    total.count.plot <- plot_samples_count(raw.count)
    samples.total.count <- colSums(raw.count)

    # Distribution of count per sample
    count.norm <- log2(count.norm+1)
    mcount <- tidyr::gather(count.norm, key = "samples", value = "count")
    legend. <- ifelse(nsamples > 30, "none", "bottom")
    count.dist.plot <- ggpubr::ggdensity(mcount, x = "count", color = "samples",
                                         main = "Count distribution per sample",
                                         xlab = "log2(count)", ylab = "Density",
                                         legend = legend.)


    # For heatmap and PCA
    # select genes with high sd and genes with expression > 5 in at least 10%
    expressed.genes <- genefilter::genefilter(rld.data,
                                              genefilter::pOverA(p = 0.1, 5))
    rld.data <- rld.data[expressed.genes, ]
    sds <- genefilter::rowSds(rld.data)
    top.var.genes <- head( order( sds, decreasing = TRUE ), 2000 )
    rld.data <- rld.data[top.var.genes, ]

    res.pca <- FactoMineR::PCA(t(rld.data), graph = FALSE)
    pca.plot <- factoextra::fviz_pca_ind(res.pca, repel = TRUE)

    heatmap. <- ComplexHeatmap::Heatmap( t(scale(t(rld.data))), name = "Exprs",
                                         show_row_names = FALSE, show_column_names = TRUE,
                                         show_row_dend = FALSE, show_column_dend = TRUE,
                                         cluster_columns = TRUE, cluster_rows = TRUE,
                                         clustering_method_columns = "complete", clustering_method_rows = "complete",
                                         column_names_gp = grid::gpar(fontsize = 7),
                                         column_title = "Heatmap"
    )


    grDevices::pdf(file.path(result.dir,  "quality.control.pdf"))
    print(total.count.plot)
    print(count.dist.plot)
    print(pca.plot)
    print(heatmap.)
    grDevices::dev.off()
  }
  else warning("No quality assessment done because the number of samples < 2", call. = FALSE)

}
