#' @include utilities.R
NULL
#' Create reports
#' @description
#' Create an html file containing some exploratory data analysis
#' @param se an object of class SummarizedExperiment generated by the function count_reads()
#' @param result_file path to the result_file prefix (e.g., path/to/prefix)
#' 
#' @export
rnaseq_eda <- function(se, result_file){
  
  if(!dir.exists(dirname(result_file))) create_dir(dirname(result_file)) 
  
  oldwd <- getwd()
  setwd(dirname(result_file))
  
  result_file <- paste(basename(result_file), "_rnaseq_eda_", 
                       format(Sys.time(), "_%Y_%m_%d_"), 
                       get_random_string(8), ".html", sep="")
  result_file <- file.path(getwd(), result_file)
  
  eda_rmd <- system.file("reports", "eda.Rmd", package = "ezRNAseq")
  rmarkdown::render(input = eda_rmd, output_file = result_file,
                    params = list(se = se))
  
  setwd(oldwd)
}

